apiVersion: v1
kind: Pod
metadata:
  name: ycsb
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - cockroachdb
          topologyKey: kubernetes.io/hostname
  containers:
  - name: ycsb
    image: cockroachdb/loadgen-ycsb
    args: ["-concurrency=256", "-splits=1000", "-tolerate-errors", "postgresql://root@cockroachdb-public:26257?application_name=ycsb&sslmode=disable"]

